[package]
name = "tiefgogy"
version = "0.1.0"
compiler = "0.13.1"
authors = ["Lena Tauchner"]
entrypoint = "lib.typ"
license = "MIT"
description = "Worksheet components for all disciplines."
keywords = []
categories = ["layout", "fun", "flyer"]
disciplines = []

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"
